services:
  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  orchestrator-db:
    image: postgres:16-alpine
    env_file:
      - path: .env
        required: false
      - path: orchestrator/.env
        required: false
    ports:
      - "5433:5432" # Changed host port to 5433
    volumes:
      - orchestrator_data:/var/lib/postgresql/data # Unique volume
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  auth-db:
    image: postgres:16-alpine
    env_file:
      - path: .env
        required: false
      - path: auth/.env
        required: false
    ports:
      - "5432:5432" # Keeps standard 5432
    volumes:
      - auth_data:/var/lib/postgresql/data # Unique volume
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  gateway:
    env_file:
      - path: .env
        required: false
      - path: gateway/.env
        required: false
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8000"  # Host 8080 -> Container 8000

  orchestrator:
    env_file:
      - path: .env
        required: false
      - path: orchestrator/.env
        required: false
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    depends_on:
      orchestrator-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8001"  # Host 8081 -> Container 8001

  auth:
    env_file:
      - path: .env
        required: false
      - path: auth/.env
        required: false
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8083:8003"  # Host 8083 -> Container 8003

  ml_worker:
    env_file:
      - path: .env
        required: false
      - path: ml_worker/.env
        required: false
    build:
      context: .
      dockerfile: ml_worker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8082:8002"  # Host 8082 -> Container 8000

volumes:
  orchestrator_data:
  auth_data:
  redis_data: