[project]
name = "ml_worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.11.0",
    "shared",
]


[tool.uv]
managed = true
package = true

[tool.uv.sources]
shared = { workspace = true }

[tool.setuptools]
packages = ["ml_worker"]
package-dir = { "ml_worker" = "." }