"""add user_id to query table

Revision ID: b9437e5aa5a0
Revises: 6b0f58a78b9c
Create Date: 2026-05-05 20:25:30.599693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9437e5aa5a0'
down_revision: Union[str, Sequence[str], None] = '6b0f58a78b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_column('queries', 'user_id')
    # ### end Alembic commands ###
