from typing import Any
from uuid import UUID

from pydantic import Field

from shared.schemas import BaseSchema


class TaskMessage(BaseSchema):
    prompt: str = Field(min_length=1, description="Prompt sent to Gemini")
    correlation_id: UUID = Field(
        description="Id for tracing the task across services, generated by gateway"
    )
    interaction_id: UUID | None = Field(
        default=None,
        description="Gemini conversation message history",
    )
    user_id: str | None = Field(default=None)
    model: str | None = Field(
        default=None, description="Optional Gemini model override"
    )
    metadata: dict[str, Any] = Field(default_factory=dict)
